version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/EBS
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8080 
    depends_on:
      - db
    networks:
      - spring-net
    volumes:
      - ./backend/src/main/resources:/app/resources

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - spring-net
    environment:
      - NODE_ENV=production
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=EBS
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data  
    ports:
      - "15432:5432"
   networks:
     - spring-net
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:9
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
   volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  postgres-data: 
  pgadmin-data:

networks:
  spring-net:
    driver: bridge
    
    
 
